# Generated by Django 2.1.2 on 2019-03-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '分类',
                'db_table': 'BookTitle',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=64)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('href', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=32)),
                ('count', models.CharField(max_length=64)),
                ('book_intro', models.TextField()),
                ('img', models.ImageField(upload_to='../static/bookimg', verbose_name='图片')),
                ('booktitle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.BookTitle')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='WordCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '30万字以下'), (1, '30-50万字'), (2, '50-100万字'), (3, '100-200万字'), (4, '200万字以上')])),
            ],
        ),
        migrations.AddField(
            model_name='novel',
            name='status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.Status'),
        ),
        migrations.AddField(
            model_name='novel',
            name='wordcount',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.WordCount'),
        ),
    ]
