# Generated by Django 2.1.2 on 2019-03-16 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='booktitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.BookTitle'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.Status'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='wordcount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.WordCount'),
        ),
    ]
