# Generated by Django 2.1.2 on 2018-10-27 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BxSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '下线'), (1, '上线')], default=1)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('img', models.ImageField(upload_to='./static/img/')),
                ('href', models.CharField(max_length=256)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '首页轮播',
                'db_table': 'BxSlider',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('weight', models.IntegerField(verbose_name='权重(从大到小排列)')),
            ],
            options={
                'verbose_name_plural': '分类',
                'db_table': 'Classfication',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(verbose_name='权重(从大到小排列)')),
                ('name', models.CharField(max_length=32)),
                ('classification', models.ManyToManyField(to='app.Classification')),
            ],
            options={
                'verbose_name_plural': '方向',
                'db_table': 'Direction',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '级别',
            },
        ),
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '下线'), (1, '上线')], default=1)),
                ('weight', models.IntegerField(default=0, verbose_name='权重（按从大到小排列）')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('data1', models.CharField(max_length=500)),
                ('data2', models.CharField(max_length=1000)),
                ('href', models.CharField(max_length=256)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '公告',
            },
        ),
        migrations.CreateModel(
            name='Reinr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('contentInt', models.CharField(max_length=256)),
                ('href', models.CharField(max_length=256)),
            ],
            options={
                'db_table': '资源介绍',
            },
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '下线'), (1, '上线')], default=1, verbose_name='状态')),
                ('title', models.CharField(max_length=32)),
                ('summary', models.CharField(max_length=32)),
                ('img', models.ImageField(upload_to='./static/video/', verbose_name='图片')),
                ('href', models.CharField(max_length=256, verbose_name='视频地址')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Classification')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Level')),
            ],
        ),
    ]
