# Generated by Django 2.1.2 on 2018-10-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_video_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='level',
            field=models.ManyToManyField(to='app.Level'),
        ),
    ]
