# Generated by Django 2.1.2 on 2018-10-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_direction_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='reinr',
            name='img',
            field=models.ImageField(default=1, upload_to='./static/img/'),
            preserve_default=False,
        ),
    ]
