# Generated by Django 2.1.2 on 2018-10-29 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_reinr_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reinr',
            name='contentInt',
        ),
        migrations.RemoveField(
            model_name='reinr',
            name='href',
        ),
        migrations.RemoveField(
            model_name='reinr',
            name='name',
        ),
    ]
