# Generated by Django 2.1.2 on 2018-10-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181029_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='reinr',
            name='name',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
