# Generated by Django 2.1.2 on 2018-10-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_reinr_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reinr',
            name='img',
            field=models.FileField(max_length=32, upload_to='static/img'),
        ),
    ]
