# Generated by Django 2.1.2 on 2018-10-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181029_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reinr',
            name='img',
            field=models.FileField(max_length=256, upload_to='static/img'),
        ),
    ]
