# Generated by Django 2.1.2 on 2019-02-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181029_1929'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reinr',
            table=None,
        ),
    ]
